/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LibraryManagementSystem;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author grgis
 */
public class ReserveBooks extends javax.swing.JFrame {

    DBconnect db = new DBconnect();
    Connection con = db.con();

    DateConverter dateadapter = new DateAdapter();
    LocalDate currentDate = LocalDate.now();
    LocalDate skippedDate = currentDate.plusDays(10);
    String outputdate = dateadapter.convertToLocalDate(skippedDate.toString());
    RentService rentService = new RentService();
    String availDate;
    String title;
    String availability;
    String user;
    int noOfBooks;
    /**
     * Creates new form ReserveBooks
     */

    ReserveService reserveService = new ReserveService();

    public ReserveBooks() {
        initComponents();
    }

    public ReserveBooks(String x) {
        initComponents();
        user = x;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        resrve_btn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "book"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        resrve_btn.setText("Reserve Book");
        resrve_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resrve_btnActionPerformed(evt);
            }
        });

        jButton1.setText("Display ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(46, 46, 46)
                .addComponent(resrve_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resrve_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resrve_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resrve_btnActionPerformed
        int row = jTable1.getSelectedRow();
        title = jTable1.getValueAt(row, 0).toString();

        try {
            PreparedStatement ps2 = con.prepareStatement("SELECT   (Select COUNT(*) AS rows1 FROM rentals where username='Rocky_12' and returndate is null) + (select COUNT(*) AS rows2 FROM reserves where username='Rocky_12' and reserved !=0 )");
            //ps2.setString(1, user);
            ResultSet rs1 = ps2.executeQuery();
            rs1.next();
            noOfBooks = rs1.getInt(1);
            if (noOfBooks > 5) {
                JOptionPane.showMessageDialog(null, "You have reached your limit");
                resrve_btn.setEnabled(false);
            } else {

                //reserveService.rentBookWhenAvailable(title, user);
                PreparedStatement ps3 = con.prepareStatement("insert into reserves(username,ReserveDate,ReservedBook,Reserved) values(?,?,?,1)");
                ps3.setString(1, user);
                ps3.setDate(2, dateadapter.convertToSqlDate(currentDate));
                ps3.setString(3, title);
                ps3.executeUpdate();
                JOptionPane.showMessageDialog(null, "Book is reserved");
                jButton1.doClick();
            }

        } catch (SQLException ex) {
            Logger.getLogger(ReserveBooks.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_resrve_btnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel tablemodel2 = (DefaultTableModel) jTable1.getModel();
        tablemodel2.setRowCount(0);
        try {

            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT title FROM books WHERE title NOT IN (SELECT ReservedBook FROM reserves) and Availability='false' and deleted=0");
            while (rs.next()) {

                title = rs.getString("title");
                tablemodel2.addRow(new Object[]{title});
            }

            stmt.close();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new UserMenu(user).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReserveBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReserveBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReserveBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReserveBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReserveBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton resrve_btn;
    // End of variables declaration//GEN-END:variables
}
