/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LibraryManagementSystem;

/**
 *
 * @author HP
 */

import java.sql.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;

public class UserRegister extends javax.swing.JFrame {
    

    
    DBconnect db = new DBconnect();
    Connection con = db.con();


    /**
     * Creates new form UserRegister
     */
    public UserRegister() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        UsrText = new javax.swing.JLabel();
        uReg_Username = new javax.swing.JTextField();
        UsrText1 = new javax.swing.JLabel();
        uReg_FirstName = new javax.swing.JTextField();
        UsrText2 = new javax.swing.JLabel();
        uReg_LastName = new javax.swing.JTextField();
        UsrText3 = new javax.swing.JLabel();
        UserRegBtn = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(102, 255, 204));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(36, 45, 65));
        jLabel1.setText("Register");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addContainerGap(693, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 80));

        UsrText.setFont(new java.awt.Font("Microsoft Tai Le", 0, 16)); // NOI18N
        UsrText.setForeground(new java.awt.Color(255, 255, 255));
        UsrText.setText("Username");
        jPanel1.add(UsrText, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 80, 50));
        jPanel1.add(uReg_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 280, 50));

        UsrText1.setFont(new java.awt.Font("Microsoft Tai Le", 0, 16)); // NOI18N
        UsrText1.setForeground(new java.awt.Color(255, 255, 255));
        UsrText1.setText("Password");
        jPanel1.add(UsrText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 80, 50));
        jPanel1.add(uReg_FirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 280, 50));

        UsrText2.setFont(new java.awt.Font("Microsoft Tai Le", 0, 16)); // NOI18N
        UsrText2.setForeground(new java.awt.Color(255, 255, 255));
        UsrText2.setText("First Name");
        jPanel1.add(UsrText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, -1, 50));
        jPanel1.add(uReg_LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 280, 50));

        UsrText3.setFont(new java.awt.Font("Microsoft Tai Le", 0, 16)); // NOI18N
        UsrText3.setForeground(new java.awt.Color(255, 255, 255));
        UsrText3.setText("Last Name");
        jPanel1.add(UsrText3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 80, 50));

        UserRegBtn.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 16)); // NOI18N
        UserRegBtn.setText("Register");
        UserRegBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserRegBtnActionPerformed(evt);
            }
        });
        jPanel1.add(UserRegBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 170, -1));

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 280, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserRegBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserRegBtnActionPerformed

        User u = new User();
        u.FirstName = uReg_FirstName.getText();
        u.LastName = uReg_LastName.getText();
        u.Password_u =jPasswordField1.getText();
        u.Username_u = uReg_Username.getText();
        
        try {
            PreparedStatement Pstatement = con.prepareStatement("insert into users (username, u_pwd, firstname, lastName) values(?,?,?,?)");
          
            // Specifying the values of it's parameter
            Pstatement.setString(1, u.Username_u);
            Pstatement.setString(2, u.Password_u);
            Pstatement.setString(3, u.FirstName);
            Pstatement.setString(4, u.LastName);
            
            Pstatement.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "User registered!");
            
            }
         catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_UserRegBtnActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UserRegBtn;
    private javax.swing.JLabel UsrText;
    private javax.swing.JLabel UsrText1;
    private javax.swing.JLabel UsrText2;
    private javax.swing.JLabel UsrText3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField uReg_FirstName;
    private javax.swing.JTextField uReg_LastName;
    private javax.swing.JTextField uReg_Username;
    // End of variables declaration//GEN-END:variables

}